name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'  # Needed for elocuent to analyze Git history

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Elocuent
        run: |
          npx elocuent -d . -o meta/loc.csv

      - name: Commit and Push CSV (only if changed)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p meta
          git pull

          # Only commit if loc.csv changed
          if ! git diff --quiet -- meta/loc.csv; then
            echo "meta/loc.csv changed — committing update"
            git add -f meta/loc.csv
            git commit -m "Update code statistics"
            git push
          else
            echo "meta/loc.csv unchanged — skipping commit."
          fi

      - name: Build site
        run: |
          # Add your static site build step here, if needed.
          echo "No build step defined."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Or your actual build output directory
